name: Publish packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build, pack & publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish essentialMix
      uses: brandedoutcast/publish-nuget@latest
      with: 
        PROJECT_FILE_PATH: essentialMix/Standard/essentialMix/essentialMix.csproj
        NUGET_KEY: oy2cpwuhyq4rpnjnyktqatrbzwooxhgetetj3xnl7qaytq
